apiVersion: v2
name: csi-cloudscale
description: A Container Storage Interface Driver for cloudscale.ch volumes.
type: application
version: 0.1.0
appVersion: 3.2.0
home: https://github.com/cloudscale-ch/csi-cloudscale
sources:
  - https://github.com/cloudscale-ch/csi-cloudscale.git
