apiVersion: v2
name: csi-cloudscale
description: A Container Storage Interface Driver for cloudscale.ch volumes.
type: application
version: 1.4.0
appVersion: "3.6.0"
home: https://github.com/cloudscale-ch/csi-cloudscale
sources:
  - https://github.com/cloudscale-ch/csi-cloudscale.git
dependencies:
  - name: common
    version: 2.34.0
    repository: https://charts.bitnami.com/bitnami

