apiVersion: v2
name: csi-cloudscale
description: A Container Storage Interface Driver for cloudscale.ch volumes.
type: application
version: 1.3.6
appVersion: "3.5.6"
home: https://github.com/cloudscale-ch/csi-cloudscale
sources:
  - https://github.com/cloudscale-ch/csi-cloudscale.git
dependencies:
  - name: common
    version: 2.31.4
    repository: https://charts.bitnami.com/bitnami

