apiVersion: v2
name: csi-cloudscale
description: A Container Storage Interface Driver for cloudscale.ch volumes.
type: application
version: 1.3.5
appVersion: "3.5.5"
home: https://github.com/cloudscale-ch/csi-cloudscale
sources:
  - https://github.com/cloudscale-ch/csi-cloudscale.git
dependencies:
  - name: common
    version: 1.17.1
    repository: https://charts.bitnami.com/bitnami

