version: 2
updates:
  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Check for Go module updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Check docker base image updates
  - package-ecosystem: "docker"
    directory: "/cmd/cloudscale-csi-plugin"
    schedule:
      interval: "weekly"
