apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: my-volume-snapshot
spec:
  volumeSnapshotClassName: cloudscale-snapshots
  source:
    persistentVolumeClaimName: my-volume
