# Secret containing the LUKS key for the restored volume
# IMPORTANT: This must use the same LUKS key as the original volume
# The secret name must follow the pattern: ${pvc-name}-luks-key
# In this case: my-restored-luks-volume-luks-key
apiVersion: v1
kind: Secret
metadata:
  name: my-restored-luks-volume-luks-key
stringData:
  luksKey: "hDEKFgEZgmpuppShPG7HailSFBsy8MzlvlhALvqk0+2jTrcKrFmtttoF5IGlLVoLt/jpaWnk/kcl7JxnsZ3xQjEcYumv4WkwOv77x+c2C/kyyldTNRaCaVHG9fW9n6oicoWzsyUWcmu0d+JOorGZ792lsS9Q5gXlCg5BD2x1MoVVr8hTQArFfUX6NuHF1o0v/EGHU0A5O5wiNnqpdDjf9r56rPt0H290Nr6Y5Ijb5RTIoJFT5ww5XocrvLlR/GiXRYgzeISfbfyIr8FpfRKmjPTZdLBSXPMMdHJNcPIlRG+DfnBaTKkIFwiWXjxXZss71IKibEM7Qfjwka0KFyufwA=="
